#!/bin/bash
./run_challenge 2023 1 1
./run_challenge 2023 1 2
./run_challenge 2023 2 1
./run_challenge 2023 2 2
./run_challenge 2023 3 1
./run_challenge 2023 3 2
./run_challenge 2023 4 1
./run_challenge 2023 4 2
./run_challenge 2023 5 1
./run_challenge 2023 5 2
./run_challenge 2023 6 1
./run_challenge 2023 6 2